### ISSUE TITLE
Example output?

### ISSUE THREAD

**Issue by chrisabrams** [incrediblesound/story-graph#1]
This project looks interesting, and maybe I'm just ignorant to the use case, but could you provide an example output of what story(s) can be generated based on the examples in the readme?

**Comment by incrediblesound** [comment]
OK I added an example of output from running the example file included in the repository as well as a simple rendering of the output from the example rule given at the end of the readme. I'll probably add more later but this should at least be a little bit better :-)

**Comment by chrisabrams** [comment]
I see now, thanks!
