### ISSUE TITLE
add eslint

### ISSUE THREAD

**Issue by flipactual** [incrediblesound/story-graph#14]
I feel like I may be stepping on some toes by not knowing the desired code styling. Any interest in adding eslint so things stay the same throughout?

**Comment by incrediblesound** [comment]
Yeah I've been meaning to do it but just haven't gotten around to it. I like the new es6 airb&b spec but it has some really strict rules in there. Perhaps we could use it and just turn off the overly strict rules?

**Comment by flipactual** [comment]
Yeah, the legacy/base airbnb config is great. Some of the rules can be fixed automatically (`--fix`) too.

**Comment by flipactual** [comment]
closed by https://github.com/incrediblesound/story-graph/pull/16
