### ISSUE TITLE
What are Type Decorators for?

### ISSUE THREAD

**Issue by flipactual** [incrediblesound/story-graph#4]
After running the scripts dozen of times, I've yet to see a Type Decorator in the outputted text. Is this intentional? bug? future feature?

**Comment by incrediblesound** [comment]
Hi Flip. First of all, thanks for your involvement! Software improves through collaboration, and it's hard to know the strengths and weaknesses of something I've written if no one comments on them. I'm excited to keep working on this project now that I'm not doing it alone!

As for this issue, I looked in ./example.txt and found this line:
"Some things are light and some are heavy."

which creates the following decorators:

``` javascript
var light = function(type){
    return type.extend('light');
}

var heavy = function(type){
    return type.extend('heavy');
}
```

But later on the line:
"A rock is a dry heavy solid."

Is rendered as:

``` javascript
var rock = solid.extend('rock')
```

Peeping into the tokenizer I found this token:

``` javascript
{ type: 'compound type',
    line: [ 'A', 'rock', 'is', 'a', 'dry', 'heavy', 'solid' ] }
```

Which suggests that compound types are not being rendered properly by the story-graph compiler. I will take a look and see if I can fix the problem.
